name: Send Email with Nodemailer

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Create .env file
        run: |
          echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> .env
          echo "GMAIL_PASS=${{ secrets.GMAIL_PASS }}" >> .env
          echo "GMAIL_TO=${{ secrets.GMAIL_TO }}" >> .env
      - name: Run emailSender.js
        run: node emailSender.js
